fun getPinMap(): Map<PinName, Pin> = mapOf(
    PinName.SDA_0 to Pin(bcm = 0, wPi = 30, physical = 27),
    PinName.SCL_0 to Pin(bcm = 1, wPi = 31, physical = 28),
    PinName.SDA_1 to Pin(bcm = 2, wPi = 8, physical = 3),
    PinName.SCL_1 to Pin(bcm = 3, wPi = 9, physical = 5),
    PinName.GPIO_4 to Pin(bcm = 4, wPi = 7, physical = 7),
    PinName.GPIO_5 to Pin(bcm = 5, wPi = 21, physical = 29),
    PinName.GPIO_6 to Pin(bcm = 6, wPi = 22, physical = 31),
    PinName.CE_1 to Pin(bcm = 7, wPi = 11, physical = 26),
    PinName.CE_0 to Pin(bcm = 8, wPi = 10, physical = 24),
    PinName.MISO to Pin(bcm = 9, wPi = 13, physical = 21),
    PinName.MOSI to Pin(bcm = 10, wPi = 12, physical = 19),
    PinName.SCLK to Pin(bcm = 11, wPi = 14, physical = 23),
    PinName.GPIO_12 to Pin(bcm = 12, wPi = 26, physical = 32),
    PinName.GPIO_13 to Pin(bcm = 13, wPi = 23, physical = 33),
    PinName.TxD to Pin(bcm = 14, wPi = 15, physical = 8),
    PinName.RxD to Pin(bcm = 15, wPi = 16, physical = 10),
    PinName.GPIO_16 to Pin(bcm = 16, wPi = 27, physical = 36),
    PinName.GPIO_17 to Pin(bcm = 17, wPi = 0, physical = 11),
    PinName.GPIO_18 to Pin(bcm = 18, wPi = 1, physical = 12),
    PinName.GPIO_19 to Pin(bcm = 19, wPi = 24, physical = 35),
    PinName.GPIO_20 to Pin(bcm = 20, wPi = 28, physical = 38),
    PinName.GPIO_21 to Pin(bcm = 21, wPi = 29, physical = 40),
    PinName.GPIO_22 to Pin(bcm = 22, wPi = 3, physical = 15),
    PinName.GPIO_23 to Pin(bcm = 23, wPi = 4, physical = 16),
    PinName.GPIO_24 to Pin(bcm = 24, wPi = 5, physical = 18),
    PinName.GPIO_25 to Pin(bcm = 25, wPi = 6, physical = 22),
    PinName.GPIO_26 to Pin(bcm = 26, wPi = 25, physical = 37),
    PinName.GPIO_27 to Pin(bcm = 27, wPi = 2, physical = 13)
)

fun Map<PinName, Pin>.bcm(name: PinName) = this[name]!!.bcm

class Pin internal constructor(val bcm: Int, val wPi: Int, val physical: Int)

enum class PinName {
    SDA_0,
    SCL_0,
    SDA_1,
    SCL_1,
    MOSI,
    MISO,
    SCLK,
    TxD,
    RxD,
    CE_0,
    CE_1,
    GPIO_4,
    GPIO_5,
    GPIO_6,
    GPIO_12,
    GPIO_13,
    GPIO_16,
    GPIO_17,
    GPIO_18,
    GPIO_19,
    GPIO_20,
    GPIO_21,
    GPIO_22,
    GPIO_23,
    GPIO_24,
    GPIO_25,
    GPIO_26,
    GPIO_27
}