rootProject.name = "RaspberryPi"
include("WaterLed")
include("common")
include("BreathingLED")
include("ColorfulLED")
include("Buzzer")
include("Alerter")
include("ADC")
include("Softlight")
include("ColorfulSoftlight")
include("Bedlamp")
